### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by math-ematics** [janreges/siteone-website-crawler#1]
Please allow --proxy=IP option to add proxy or allow for a file with proxys or even pipe thu TOR

**Comment by janreges** [comment]
Hi,

now you can use `--proxy=host:port`.

Thanks for the idea to use more proxies. I can add `--proxy-list=IP1,IP2,...` and `--proxy-list-file=proxies.txt`.

Do you also have a concrete idea how this should work in case of defining more proxies?

I can think of for example the possibility of `--proxy-strategy` with the value `random` or `round-robin` and some directive that would control the behavior in case it would be necessary to retry the request with another proxy due to a broken proxy.
